# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='capacity',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('turn', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerf_15.factories')),
            ],
        ),
        migrations.CreateModel(
            name='selling_price',
            fields=[
                ('spid', models.AutoField(primary_key=True, serialize=False)),
                ('turn', models.IntegerField()),
                ('selling_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beerf_15.users')),
            ],
        ),
        migrations.AddField(
            model_name='factory_retailer',
            name='popularity',
            field=models.DecimalField(decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='retailers',
            name='zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selling_price',
            name='frid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerf_15.factory_retailer'),
        ),
    ]
