# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beerf_15.factories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
