# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0002_db restructuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='factories',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retailers',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='retailers',
            name='unlocked',
            field=models.IntegerField(default=0),
        ),
    ]
