# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0002_changed_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beerf_15.factories'),
        ),
    ]
