# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0004_inventory_log_money_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_log',
            old_name='change',
            new_name='inventory_change',
        ),
        migrations.RenameField(
            model_name='money_log',
            old_name='change',
            new_name='money_change',
        ),
    ]
