# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0004_Add amount column to factories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factories',
            name='fcode',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='retailers',
            name='rcode',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
