# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0005_auto_20160113_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_log',
            old_name='ifid',
            new_name='fid',
        ),
        migrations.RenameField(
            model_name='money_log',
            old_name='mfid',
            new_name='fid',
        ),
    ]
