# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0006_auto_20160113_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailers',
            name='rcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
