# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0007_auto_20160129_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='popularity_log',
            fields=[
                ('popid', models.AutoField(primary_key=True, serialize=False)),
                ('turn', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('frid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerf_15.factory_retailer')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('scoreid', models.AutoField(primary_key=True, serialize=False)),
                ('turn', models.IntegerField()),
                ('score', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerf_15.users')),
            ],
        ),
    ]
