# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerf_15', '0008_popularity_log_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='prag_fullname',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='prag_userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='prag_username',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
